[general]
import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]
live_config_reload = true

[window]
padding.x = 10
padding.y = 10
opacity = 0.9
decorations = "Full"

[font]
normal.family = "monospace"
size = 14.0

[colors]
primary.background = "#282828"
primary.foreground = "#ebdbb2"
