# ==================================================
# TRUECOLOR
# ==================================================

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# ==================================================
# STATUS BAR
# ==================================================

set -g status on
set -g status-position bottom
set -g status-interval 1

set -g status-style "bg=#07141a,fg=#d6deeb"

set -g status-left-length 100
set -g status-right-length 100

# ==================================================
# LEFT SIDE
# ==================================================

set -g status-left \
"#[fg=#07141a,bg=#82aaff,bold] SESSION #[fg=#82aaff,bg=#102028,nobold] #S "

# ==================================================
# WINDOWS
# ==================================================

setw -g window-status-separator ""

# inactive
setw -g window-status-format \
"#[fg=#5c6773,bg=#07141a] #I:#W "

# active
setw -g window-status-current-format \
"#[fg=#07141a,bg=#5fd7ff,bold] #I:#W "

# activity
setw -g window-status-activity-style \
"fg=#ffd787,bg=#07141a"

# bell
setw -g window-status-bell-style \
"fg=#ff5f87,bg=#07141a,bold"

# ==================================================
# RIGHT SIDE
# ==================================================

set -g status-right \
"#[fg=#82aaff,bold] %H:%M #[fg=#3b4a55]│ #[fg=#89ddff] %a #[fg=#5fd7ff]%d %b "
# ==================================================
# PANE BORDERS
# ==================================================

set -g pane-border-style \
"fg=#1a2a33"

set -g pane-active-border-style \
"fg=#82aaff"

# ==================================================
# MESSAGE STYLE
# ==================================================

set -g message-style \
"fg=#07141a,bg=#82aaff"

# ==================================================
# COPY MODE
# ==================================================

set -g mode-style \
"fg=#07141a,bg=#ffd787"
